from PyQt5 import QtCore, QtGui, QtWidgets


############ basic layout/GUI for the application #################################

### islaidu_tipai input widget/dialog ###
class Ui_IslTipForma(object):
    def setupUi(self, islaidos_tipai_forma):
        islaidos_tipai_forma.setObjectName("isl_dialog")
        islaidos_tipai_forma.resize(392, 330)
        self.pushButton = QtWidgets.QPushButton(islaidos_tipai_forma)
        self.pushButton.setGeometry(QtCore.QRect(70, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(islaidos_tipai_forma)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 230, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(islaidos_tipai_forma)
        self.lineEdit.setGeometry(QtCore.QRect(40, 120, 301, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(islaidos_tipai_forma)
        self.label.setGeometry(QtCore.QRect(150, 90, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(islaidos_tipai_forma)
        QtCore.QMetaObject.connectSlotsByName(islaidos_tipai_forma)

    def retranslateUi(self, islaidos_tipai_forma):
        _translate = QtCore.QCoreApplication.translate
        islaidos_tipai_forma.setWindowTitle(
            _translate("islaidos_tipai_forma", "Dialog"))
        self.pushButton.setText(_translate("islaidos_tipai_forma", "Saugoti"))
        self.pushButton_2.setText(_translate(
            "islaidos_tipai_forma", "Uždaryti"))
        self.lineEdit.setPlaceholderText(_translate(
            "islaidos_tipai_forma", "įvesti (abc,123)"))
        self.label.setText(_translate("islaidos_tipai_forma", "Pavadinimas:"))


# main windows application layout (without external widgets)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # main window size parameters
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 1200))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 1200))

        # central widget, main screen
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(125, 0, 31, 1201))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        # meniu action buttons and text widgets
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 30, 141, 41))
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 70, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 110, 141, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Meniu = QtWidgets.QLabel(self.centralwidget)
        self.Meniu.setGeometry(QtCore.QRect(0, 0, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Meniu.setFont(font)
        self.Meniu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Meniu.setScaledContents(False)
        self.Meniu.setAlignment(QtCore.Qt.AlignCenter)
        self.Meniu.setObjectName("Meniu")

        # stacked widget area , where different screens (depending what area are chosen (menu option)) are stacked on each other
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 0, 1451, 1191))
        self.stackedWidget.setObjectName("stackedWidget")

        # the 'database hasn't been connected screen' , in case there is no active local db connection setup
        self.pageNoData = QtWidgets.QWidget()
        self.pageNoData.setObjectName("pageNoData")
        self.label = QtWidgets.QLabel(self.pageNoData)
        self.label.setGeometry(QtCore.QRect(460, 330, 461, 341))
        font = QtGui.QFont()
        font.setPointSize(25)

        # 'pradzia'page
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.pageNoData)
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.label_2 = QtWidgets.QLabel(self.pageHome)
        self.label_2.setGeometry(QtCore.QRect(720, 250, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.pushButtonIslaidosMain = QtWidgets.QPushButton(self.pageHome)
        self.pushButtonIslaidosMain.setGeometry(
            QtCore.QRect(640, 390, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonIslaidosMain.setFont(font)
        self.pushButtonIslaidosMain.setObjectName("pushButtonIslaidosMain")
        self.nasumas_label = QtWidgets.QLabel(self.pageHome)
        self.nasumas_label.setGeometry(QtCore.QRect(490, 90, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nasumas_label.setFont(font)
        self.nasumas_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nasumas_label.setObjectName("nasumas_label")
        self.label_3 = QtWidgets.QLabel(self.pageHome)
        self.label_3.setGeometry(QtCore.QRect(600, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        # 'Nustatymai' page
        self.stackedWidget.addWidget(self.pageHome)
        self.pageNustatymai = QtWidgets.QWidget()
        self.pageNustatymai.setObjectName("pageNustatymai")
        self.pushButton_4 = QtWidgets.QPushButton(self.pageNustatymai)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 60, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        # IslaiduTipai table
        self.tableWidgetIslaidos = QtWidgets.QTableWidget(self.pageNustatymai)
        self.tableWidgetIslaidos.setGeometry(QtCore.QRect(200, 250, 961, 571))
        self.tableWidgetIslaidos.setObjectName("tableWidgetIslaidos")
        self.tableWidgetIslaidos.setColumnCount(2)
        self.tableWidgetIslaidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIslaidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetIslaidos.setHorizontalHeaderItem(1, item)
        self.tableWidgetIslaidos.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetIslaidos.horizontalHeader().setDefaultSectionSize(450)
        self.tableWidgetIslaidos.verticalHeader().setMinimumSectionSize(30)
        self.stackedWidget.addWidget(self.pageNustatymai)

        # 'Islaidos' page
        self.pageIslaidos = QtWidgets.QWidget()
        self.pageIslaidos.setObjectName("pageIslaidos")
        self.dateEditFrom = QtWidgets.QDateEdit(self.pageIslaidos)
        self.dateEditFrom.setGeometry(QtCore.QRect(500, 220, 111, 31))
        self.dateEditFrom.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEditFrom.setCalendarPopup(True)
        self.dateEditFrom.setCurrentSectionIndex(0)
        self.dateEditFrom.setObjectName("dateEditFrom")
        self.label_5 = QtWidgets.QLabel(self.pageIslaidos)
        self.label_5.setGeometry(QtCore.QRect(440, 220, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.pageIslaidos)
        self.label_6.setGeometry(QtCore.QRect(700, 220, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dateEditTo = QtWidgets.QDateEdit(self.pageIslaidos)
        self.dateEditTo.setGeometry(QtCore.QRect(750, 220, 111, 31))
        self.dateEditTo.setDateTime(QtCore.QDateTime(
            QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 7, 0)))
        self.dateEditTo.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEditTo.setCalendarPopup(True)
        self.dateEditTo.setCurrentSectionIndex(0)
        self.dateEditTo.setTimeSpec(QtCore.Qt.UTC)
        self.dateEditTo.setObjectName("dateEditTo")
        self.label_7 = QtWidgets.QLabel(self.pageIslaidos)
        self.label_7.setGeometry(QtCore.QRect(640, 150, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.pageIslaidos)
        self.label_8.setGeometry(QtCore.QRect(640, 270, 47, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.pageIslaidos)
        self.pushButton_5.setGeometry(QtCore.QRect(1030, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.line_2 = QtWidgets.QFrame(self.pageIslaidos)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 1491, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.pageIslaidos)
        self.label_4.setGeometry(QtCore.QRect(640, 50, 47, 14))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(self.pageIslaidos)
        self.line_3.setGeometry(QtCore.QRect(0, 130, 1451, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.checkBox = QtWidgets.QCheckBox(self.pageIslaidos)
        self.checkBox.setGeometry(QtCore.QRect(30, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.pageIslaidos)
        self.checkBox_2.setGeometry(QtCore.QRect(410, 300, 101, 41))
        self.checkBox_2.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.pageIslaidos)
        self.checkBox_3.setGeometry(QtCore.QRect(530, 310, 101, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.pageIslaidos)
        self.checkBox_4.setGeometry(QtCore.QRect(670, 310, 101, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.pageIslaidos)
        self.checkBox_5.setGeometry(QtCore.QRect(820, 310, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.pageIslaidos)
        self.pushButton_6.setGeometry(QtCore.QRect(1030, 300, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.pageIslaidos)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 430, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.line_4 = QtWidgets.QFrame(self.pageIslaidos)
        self.line_4.setGeometry(QtCore.QRect(-3, 380, 1461, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tableView = QtWidgets.QTableView(self.pageIslaidos)
        self.tableView.setGeometry(QtCore.QRect(20, 530, 941, 621))
        self.tableView.setObjectName("tableView")
        self.graphicsView = QtWidgets.QGraphicsView(self.pageIslaidos)
        self.graphicsView.setGeometry(QtCore.QRect(970, 530, 471, 621))
        self.graphicsView.setObjectName("graphicsView")
        self.stackedWidget.addWidget(self.pageIslaidos)

        # status bar and default menu area (default menu = False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # naming function for layout properties
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Pradžia"))
        self.pushButton_2.setText(_translate("MainWindow", "Nustatymai"))
        self.pushButton_3.setText(_translate("MainWindow", "Išlaidos"))
        self.Meniu.setText(_translate("MainWindow", "Meniu"))
        self.label.setText(_translate(
            "MainWindow", "Patikrinkite , ar yra veikianti duomenų bazė"))
        self.label_2.setText(_translate("MainWindow", "250,12 €"))
        self.pushButtonIslaidosMain.setText(
            _translate("MainWindow", "pridėti išlaidas"))
        self.nasumas_label.setText(_translate("MainWindow", "Įmonės našumas"))
        self.label_3.setText(_translate("MainWindow", "Išlaidos:"))
        self.pushButton_4.setText(_translate("MainWindow", "pridėti tipą"))
        item = self.tableWidgetIslaidos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pavadinimas"))
        item = self.tableWidgetIslaidos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Aktyvus"))
        self.label_5.setText(_translate("MainWindow", "Nuo:"))
        self.label_6.setText(_translate("MainWindow", "Iki:"))
        self.label_7.setText(_translate("MainWindow", "DATA"))
        self.label_8.setText(_translate("MainWindow", "arba"))
        self.pushButton_5.setText(_translate("MainWindow", "ieškoti"))
        self.label_4.setText(_translate("MainWindow", "TIPAS"))
        self.checkBox.setText(_translate("MainWindow", "Visi"))
        self.checkBox_2.setText(_translate("MainWindow", "Šiandien"))
        self.checkBox_3.setText(_translate("MainWindow", "Ši savaitė"))
        self.checkBox_4.setText(_translate("MainWindow", "Šis mėnuo"))
        self.checkBox_5.setText(_translate("MainWindow", "Praėjęs mėnuo"))
        self.pushButton_6.setText(_translate("MainWindow", "ieškoti"))
        self.pushButton_7.setText(_translate("MainWindow", "pridėti"))
